### ISSUE TITLE
Secret "cnf-default-cert" not implemented

### ISSUE THREAD

**Issue by rreisim** [akraino-edge-stack/icn-sdwan#4]
icn-sdwan/platform/crd-ctrlr/examples/cnf-deployment.yaml does not have the "cnf-default-cert" secret manifest created.

Manifest deployment error 
"Warning  FailedMount  5m36s (x23 over 36m)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "cnf-default-cert" not found".

Greetings.

**Comment by Airren** [comment]
I am unfamiliar with this version, but it seems you haven't created the certificate for cnf. Try use this yaml to create cert.
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cnf-root-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cnf-root-cert
  namespace: default
spec:
  commonName: "sdwan"
  duration: 17520h
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: cnf-root-issuer
  secretName: cnf-root-cert

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cnf-default-issuer
  namespace: default
spec:
  ca: 
    secretName: cnf-root-cert

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cnf-default-cert
  namespace: default
spec:
  commonName: "*.default.pod.cluster.local"
  duration: 17520h
  isCA: false
  dnsNames:
  - "*.default.pod.cluster.local"
  issuerRef:
    kind: Issuer
    name: cnf-default-issuer
  secretName: cnf-default-cert

```
