### ISSUE TITLE
Connection established but no communication between hub and nodes, ping failed.

### ISSUE THREAD

**Issue by rreisim** [akraino-edge-stack/icn-sdwan#6]
Hello all, 

I am opening this thread to explain a problem I am having with the environment configuration that I can't get to work. I will try to explain it in the best way I can. 

I have 3 virtual machines, one acting as a hub and the other two as communicator nodes. The machines have the next configuration:

**HUB:**

- net0: 172.16.70.40 -- Use for internal communication
- net1: 10.151.128.119
- net2: 10.10.70.40 -- Use for sd-wan comunnication between hub and nodes.

Additionaly, it has been defined the following files to implement IPSEC tunnel:

**ipsec-proposal:**
```
apiVersion: batch.sdewan.akraino.org/v1alpha1
kind: IpsecProposal
metadata:
  labels:
    emco/deployment-id: 928486943740215855-hub1-app
    sdewanPurpose: base
    targetCluster: Hub.hub1
  name: proposal1
spec:
  dh_group: modp4096
  encryption_algorithm: aes256
  hash_algorithm: sha256
  name: proposal1
```

**ipsec-config:**
```
apiVersion: batch.sdewan.akraino.org/v1alpha1
kind: IpsecSite
metadata:
  labels:
    emco/deployment-id: 3720661577566571837-hub1-app
    sdewanPurpose: base
    targetCluster: Hub.hub1
  name: hub1device1
  namespace: default
spec:
  authentication_method: psk
  connections:
  - conn_type: tunnel
    crypto_proposal:
    - proposal1
    local_subnet: 0.0.0.0/0
    local_updown: /etc/updown
    mark: "30"
    mode: start
    name: Conndevice1_16052400
    remote_sourceip: 160.52.40.1
  crypto_proposal:
  - proposal1
  force_crypto_proposal: "0"
  local_identifier: CN=hub-hub1-cert
  pre_shared_key: "1234"
  remote: '%any'
  remote_identifier: CN=device-device1-cert
  type: VTI-based
---
apiVersion: batch.sdewan.akraino.org/v1alpha1
kind: IpsecSite
metadata:
  labels:
    emco/deployment-id: 3720661577566571838-hub1-app
    sdewanPurpose: base
    targetCluster: Hub.hub1
  name: hub1device2
  namespace: default
spec:
  authentication_method: psk
  connections:
  - conn_type: tunnel
    crypto_proposal:
    - proposal1
    local_subnet: 0.0.0.0/0
    local_updown: /etc/updown
    mark: "30"
    mode: start
    name: Conndevice2_16052402
    remote_sourceip: 160.52.40.2
  crypto_proposal:
  - proposal1
  force_crypto_proposal: "0"
  local_identifier: CN=hub-hub1-cert
  pre_shared_key: "1234"
  remote: '%any'
  remote_identifier: CN=device-device2-cert
  type: VTI-based

```

**Node edge-1:**

- net0: 172.16.70.42 -- Use for internal communication
- net1: 10.151.128.100
- net2: 10.10.70.42 -- Use for sd-wan comunnication between hub and nodes.

Additionaly, it has been defined the following files to implement IPSEC tunnel:

**ipsec-proposal:**
```
apiVersion: batch.sdewan.akraino.org/v1alpha1
kind: IpsecProposal
metadata:
  labels:
    sdewanPurpose: base
    targetCluster: Device.device1
  name: proposal1
spec:
  dh_group: modp4096
  encryption_algorithm: aes256
  hash_algorithm: sha256
  name: proposal1
```

**ipsec-config:**
```
apiVersion: batch.sdewan.akraino.org/v1alpha1
kind: IpsecHost
metadata:
  labels:
    emco/deployment-id: 3720661577566571836-device1-app
    sdewanPurpose: base
    targetCluster: Device.device1
  name: device1hub1
  namespace: default
spec:
  authentication_method: psk
  connections:
  - conn_type: tunnel
    crypto_proposal:
    - proposal1
    local_sourceip: '%config'
    local_updown: /etc/updown_oip
    mode: start
    name: Connhub1_10107040
    remote_subnet: 0.0.0.0/0
  crypto_proposal:
  - proposal1
  force_crypto_proposal: "1"
  local_identifier: CN=device-device1-cert
  pre_shared_key: "1234"
  remote: 10.10.70.40
  remote_identifier: CN=hub-hub1-cert
  type: policy-based
```

For this 2 examples, we got an IP in node edge-1, shows executing the following command 

```
bash-5.1$ sudo ip address show net2
6: net2@if74: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 00:00:00:95:89:f0 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.10.70.42/24 brd 10.10.70.255 scope global net2
       valid_lft forever preferred_lft forever
    inet 160.52.40.1/32 scope global net2
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe95:89f0/64 scope link 
       valid_lft forever preferred_lft forever
```

Additionaly, we can show the sucess of the operation executing the command of ipsec configuration

```
bash-5.1$ sudo ipsec statusall
Status of IKE charon daemon (strongSwan 5.9.2, Linux 5.15.0-58-generic, x86_64):
  uptime: 1 second, since Feb 20 11:21:32 2023
  worker threads: 11 of 16 idle, 5/0/0/0 working, job queue: 0/0/0/0, scheduled: 6
  loaded plugins: charon aes des rc2 sha2 sha1 md5 random nonce x509 revocation constraints pubkey pkcs1 pgp dnskey sshkey pem af-alg fips-prf gmp xcbc hmac attr kernel-netlink resolve socket-default connmark stroke updown xauth-generic
Listening IP addresses:
  10.210.151.134
  10.10.70.42
  172.16.70.42
  10.151.128.100
Connections:
device1hub1-Connhub1_10107040:  %any...10.10.70.40  IKEv2, dpddelay=30s
device1hub1-Connhub1_10107040:   local:  [CN=device-device1-cert] uses pre-shared key authentication
device1hub1-Connhub1_10107040:   remote: [CN=hub-hub1-cert] uses pre-shared key authentication
device1hub1-Connhub1_10107040:   child:  dynamic === 0.0.0.0/0 TUNNEL, dpdaction=restart
Security Associations (1 up, 0 connecting):
device1hub1-Connhub1_10107040[1]: ESTABLISHED 1 second ago, 10.10.70.42[CN=device-device1-cert]...10.10.70.40[CN=hub-hub1-cert]
device1hub1-Connhub1_10107040[1]: IKEv2 SPIs: 41335058a11450b2_i* 27adc8cbc4424a57_r, pre-shared key reauthentication in 2 hours
device1hub1-Connhub1_10107040[1]: IKE proposal: AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_4096
device1hub1-Connhub1_10107040{1}:  INSTALLED, TUNNEL, reqid 1, ESP SPIs: c7bc6ef4_i c35718a2_o
device1hub1-Connhub1_10107040{1}:  AES_CBC_256/HMAC_SHA2_256_128, 0 bytes_i, 0 bytes_o, rekeying in 45 minutes
device1hub1-Connhub1_10107040{1}:   160.52.40.1/32 === 0.0.0.0/0
```

In both cases, we apparently managed to successfully add the corresponding ip to the ipsec configuration.

The problem appears when we try to interact with this ip, I can't ping neither inside the pod itself nor from the hub. I don't know what the problem is here and for the autoconfiguration of the pod, I can't control the own traffic.

```
bash-5.1$ sudo ping 160.52.40.1
PING 160.52.40.1 (160.52.40.1): 56 data bytes
```

Regards, Raul.
